"""
FastAPI service — exposes the BrightEdge crawler as a REST API.

Endpoints:
  GET /               → service info
  GET /health         → health check (used by load balancers / Cloud Run)
  GET /crawl?url=...  → crawl a URL, return structured JSON
  GET /docs           → interactive Swagger UI (auto-generated by FastAPI)
"""

from fastapi import FastAPI, Query
from fastapi.responses import JSONResponse
from fastapi.middleware.cors import CORSMiddleware

from crawler import crawl

app = FastAPI(
    title="BrightEdge Web Crawler",
    description="""
## BrightEdge URL Crawler — Part 1

Given **any URL**, this service runs a three-stage pipeline:

1. **Fetch** — HTTP GET, follows redirects, handles SSL and timeouts
2. **Extract** — parses HTML, pulls title, description, OpenGraph tags, headings, body text
3. **Classify** — RAKE keyword extraction for topics, rule-based category detection

---

### Quick test URLs

- `https://www.amazon.com/Cuisinart-CPT-122-Compact-2-Slice-Toaster/dp/B009GQ034C`
- `http://blog.rei.com/camp/how-to-introduce-your-indoorsy-friend-to-the-outdoors/`
- `https://www.cnn.com/2025/09/23/tech/google-study-90-percent-tech-jobs-ai`
- `https://www.walmart.com`
- `https://www.bestbuy.com`
""",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET"],
    allow_headers=["*"],
)


@app.get("/", include_in_schema=False)
def root():
    return {
        "service":          "BrightEdge Web Crawler",
        "version":          "1.0.0",
        "usage":            "GET /crawl?url=<any_url>",
        "interactive_docs": "/docs",
        "health":           "/health",
    }


@app.get("/health", summary="Health check")
def health():
    """Returns 200 OK when the service is running.
    Used by Cloud Run and load balancers to verify the instance is alive.
    """
    return {"status": "ok"}


@app.get("/crawl", summary="Crawl a URL and extract metadata + topics")
def crawl_url(
    url: str = Query(
        ...,
        description="The URL to crawl. HTTP and HTTPS supported.",
        example="https://www.amazon.com/Cuisinart-CPT-122-Compact-2-Slice-Toaster/dp/B009GQ034C",
    )
):
    """
    Crawl the given URL and return structured metadata.

    **Response fields:**
    - Identity: `url`, `final_url`, `domain`, `canonical_url`
    - Crawl context: `status_code`, `crawled_at`, `html_hash`, `crawl_duration_ms`
    - Head signals: `language`, `title`, `meta_description`, `og_type`, `published_date`
    - Structure: `h1_tags`, `h2_tags`, `word_count`, `body_text_preview`
    - Intelligence: `topics`, `page_category`

    **Error handling:** failed crawls return a structured response with
    `status_code: 0` and an `error` field — never an HTTP 500.
    """
    if not url.startswith(("http://", "https://")):
        url = "https://" + url

    result = crawl(url)
    return JSONResponse(content=result.to_dict())
